import {collection, getDocs} from "firebase/firestore";
import type {NextPage} from "next";
import Head from "next/head";
import Image from "next/image";
import {useContext, useEffect} from "react";
import RestaurantCarousel from "../components/RestaurantCarousel";
import {AuthContext} from "../firebase/AuthContext";
import {StoreContext} from "../firebase/StoreContext";
import useRestaurants from "../hooks/useRestaurants";
import useUserRestaurants from "../hooks/useUserRestaurants";
import {Restaurant} from "../interfaces";

const Card = (props: {title: string; href: string; text: string}) => (
	<a
		href={props.href}
		className="m-4 p-6 text-left no-underline rounded-xl max-w-xs border-gray-100 border-2 hover:text-blue-500 hover:border-blue-500 focus:text-blue-500 focus:border-blue-500 active:text-blue-500 active:border-blue-500">
		<h2 className="m-0 mb-4 text-2xl">{props.title} &rarr;</h2>
		<p className="m-0 text-xl">{props.text}</p>
	</a>
);

const Home: NextPage = () => {
	const {user} = useContext(AuthContext);
	const {restaurants, isLoading: isLoadingRestaurants} = useRestaurants();
	const {userRestaurants, isLoading: isUserRestaurantsLoading} = useUserRestaurants(user);

	useEffect(() => {
		console.log(user);
	}, [user]);

	useEffect(() => {
		console.log({userRestaurants});
	}, [userRestaurants]);

	const completeRestaurant = (restaurant: Restaurant) => {
		const userRestaurant = userRestaurants.find((item) => restaurant.id === item.restaurantID);
		return {...restaurant, qrCode: userRestaurant.qrCode, userAmount: userRestaurant.userAmount};
	};

	return (
		<div className="h-screen w-full bg-gray-100 relative">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="h-screen w-full flex flex-col items-center justify-center">
				<h1 className="m-0 text-7xl font-bold text-gray-700 absolute top-24">Streaks</h1>
				<RestaurantCarousel restaurants={restaurants.map(completeRestaurant)} />
			</main>

			<footer className="flex py-8 px-0 border-t-2 border-t-gray-100 items-center justify-center">
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					className="flex justify-center items-center flex-grow"
					rel="noopener noreferrer">
					Powered by{" "}
					<span className="h-4 ml-2">
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
